# Generated by Django 4.2.16 on 2026-06-28 13:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("basic", "Básica"), ("specific", "Específica")],
                        default="specific",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topics",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
                "ordering": ["name"],
                "unique_together": {("subject", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.SlugField(blank=True, unique=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("text", models.TextField()),
                ("context_text", models.TextField(blank=True, null=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("board", models.CharField(blank=True, max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="questions.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="questions.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "ordering": ["subject", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "ordering": ["letter"],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "topic", "difficulty", "is_active"],
                name="questions_q_subject_a42fed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["board", "year"], name="questions_q_board_3c2001_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alternative",
            unique_together={("question", "letter")},
        ),
    ]
