# Generated by Django 4.2.16 on 2026-06-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("master_file", models.CharField(max_length=80)),
                (
                    "study_phase",
                    models.CharField(
                        choices=[
                            ("1", "Fase 1 — Leitura"),
                            ("2", "Fase 2 — Consolidação"),
                            ("3", "Fase 3 — Treino de Prova"),
                            ("4", "Fase 4 — Reta Final"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("specific", "Específica"), ("basic", "Básica")],
                        default="specific",
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_module",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo de Estudo",
                "verbose_name_plural": "Módulos de Estudo",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudyChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("order", models.PositiveSmallIntegerField()),
                ("content", models.TextField(blank=True)),
                ("key_points", models.TextField(blank=True)),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=30)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("sections_source", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="study_plan.studymodule",
                    ),
                ),
                (
                    "related_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="study_chapters",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capítulo",
                "verbose_name_plural": "Capítulos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Não iniciado"),
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluído"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="study_plan.studychapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Lição",
                "verbose_name_plural": "Progressos de Lição",
            },
        ),
        migrations.AddIndex(
            model_name="studymodule",
            index=models.Index(fields=["order"], name="study_plan__order_a75bb5_idx"),
        ),
        migrations.AddIndex(
            model_name="studymodule",
            index=models.Index(
                fields=["category"], name="study_plan__categor_63ce0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymodule",
            index=models.Index(
                fields=["study_phase"], name="study_plan__study_p_70e5c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studychapter",
            index=models.Index(
                fields=["module", "order"], name="study_plan__module__a26188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studychapter",
            index=models.Index(
                fields=["module", "is_active"], name="study_plan__module__b79c24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studychapter",
            unique_together={("module", "slug"), ("module", "order")},
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["user", "status"], name="study_plan__user_id_56f9ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["user", "completed_at"], name="study_plan__user_id_35519c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "chapter")},
        ),
    ]
