# Generated by Django 4.2.16 on 2026-06-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidedReflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("what_understood", models.TextField()),
                ("most_important", models.TextField()),
                ("most_difficult", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="study_plan.studychapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guided_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflexão Guiada",
                "verbose_name_plural": "Reflexões Guiadas",
                "indexes": [
                    models.Index(
                        fields=["user", "chapter"],
                        name="study_plan__user_id_ea3272_idx",
                    )
                ],
                "unique_together": {("user", "chapter")},
            },
        ),
        migrations.CreateModel(
            name="ActiveLearningNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="study_plan.studychapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_learning_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Aprendizagem Ativa",
                "verbose_name_plural": "Notas de Aprendizagem Ativa",
                "indexes": [
                    models.Index(
                        fields=["user", "chapter"],
                        name="study_plan__user_id_45b885_idx",
                    )
                ],
                "unique_together": {("user", "chapter")},
            },
        ),
    ]
