# Generated by Django 4.2.26 on 2026-06-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_errornotebookentry'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_plan', '0002_activelearningnote_guidedreflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorNotebookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wrong_count', models.PositiveSmallIntegerField(default=1)),
                ('last_wrong_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('personal_note', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('last_user_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.useranswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_notebook_entries', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_notebook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada do Caderno de Erros',
                'verbose_name_plural': 'Entradas do Caderno de Erros',
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='study_plan__user_id_c0a6d2_idx'), models.Index(fields=['user', 'wrong_count'], name='study_plan__user_id_68d297_idx'), models.Index(fields=['user', 'is_reviewed'], name='study_plan__user_id_6ecd67_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
