# Generated by Django 4.2.26 on 2026-06-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_activelearningnote_guidedreflection'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_quizzes', to='study_plan.studychapter'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Treino'), ('simulated', 'Simulado'), ('mini', 'Mini Quiz')], default='practice', max_length=15),
        ),
    ]
